name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Setup repo
      run: |
        make setup_repo
    - name: Update Python tools
      run: |
        bash -c "source .venv/bin/activate && python -m pip install --upgrade pip"
    - name: Install dependencies
      run: |
        bash -c "source .venv/bin/activate && make setup_pipeline"
    - name: Lint with flake8
      run: |
        bash -c "source .venv/bin/activate && make flake8"
    - name: Test
      run: |
        bash -c "source .venv/bin/activate && make verify_commit"
